config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get '/about', to: 'static_pages_#about' # Custom route
  resources :pages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    # Return array pages
    @pages = Page.all
    # Renders index.html.erb
  end

  def show
    # Return single page with a certain ID
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
    # Creates only in memory
  end

  def edit

  end

  def create
    @page = Page.new(pages_params)
    if @page.save
      redirect_to pages_path
    else
      render :new
    end
  end

  private
  def pages_params
    # {page: {title: 'post', author: 'you', body: 'asdfasdf'}}
    params.require(:page).permit(:title, :author, :body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', 'root_path' %>
<%= link_to 'About', 'about_path' %>
<%= link_to 'Pages', 'pages_path' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogSum20</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

<% @pages.each do |page| %>
    <%= page.title %>
    <%= link_to 'Show Page', page_path(page) %>
    <br>
<% end %>

<%= link_to 'New Page', new_page_path %>

<!-- erb embedded ruby-->
<!-- <%# non-echoing tag %>
<%#=  echoing tag %> -->
<!--echoing is to display ruby logic
non-echoing is logic you don't want displayed-->

app/views/pages/new.html.erb
<h1>New Page</h1>
<%= form_for @page do |f|  %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :author %>
    <%= f.text_field :author %>

    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.submit %>
<% end %>

app/views/pages/show.html.erb
<h1>TItle: <%= @page.title %></h1>
<h2>Author: <%= @page.author %></h2>
<%= @page.body %>
<%= link_to 'back', pages_path %>

app/views/static_pages/about.html.erb
<h1>About Page</h1>
<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. 
    Corrupti consectetur esse deserunt natus ipsum laborum, quidem eos 
    quaerat accusantium mollitia asperiores aperiam sunt facere 
    consequuntur sit placeat, quae nostrum optio?</p>

app/views/static_pages/home.html.erb
<h1>Home Page</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
    Consequuntur similique officiis magni est voluptas. At reiciendis 
    odit tempora veniam officiis ipsum ab aliquam accusantium quibusdam 
    iure. Nostrum aliquam dolorem ex.</p>